title: Josué Molina
logo: "/images/logo.png?raw=true" # your photo (or logo) here

description: > # your text below (remove <br> elements if you don't need line breaks)
  <strong>Data Analyst | Musician </strong>
  
  <a href="mailto:jmpmolina12@gmail.com">Email me</a>
  
  <a href="https://www.linkedin.com/in/josué-molina-90ba991a9">View My LinkedIn Profile</a> <br><br>
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
